name: meds
description: Rewrite Meds application for code reorganization.

version: 0.6.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  provider: ^4.3.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.8
  sized_context: ^0.2.1+1
  get_it: ^4.0.4
  network_to_file_image: ^2.3.1
  path_provider: ^1.6.11
  drop_cap_text: ^1.0.7
  google_fonts: ^1.1.0
  xml: ^4.2.0
  mask_text_input_formatter: ^1.0.7
  flutter_page_transition: ^0.1.6
  dropdown_suggestions_form_field: ^1.0.3

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: 'assets/meds.png'
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/meds.png
    - assets/drug.jpg
    - assets/doctor.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
